server:
  port: 8050
  contextPath: /zuul
spring:
  application:
    name: apchy-zuul
eureka:
  instance:
    #是否显示主机得IP
    perfer-ip-address: true
    #将status中得内容显示为“IP:端口“
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
zuul:
  #ignoredServices: '*'
  #ignoredPatterns: /**/admin/**
  routes:
    order-service: #zuul唯一标识
      path: /order-service/** #需要映射的路劲
      service-id: apchy-order #Eureka中的服务名称
    user-service: #zuul唯一标识
      path: /user-service/** #需要映射的路劲
      service-id: apchy-user #Eureka中的服务名称
#下面是进行负载均衡
ribbon:
  eureka:
    enabled: false
apchy-user:
  ribbon:
    listOfServers: http://localhost:8000,http://localhost:8001