server:
  port: 7900
  contextPath: /
spring:
  application:
    name: apchy-order
eureka:
  instance:
    #是否显示主机得IP
    perfer-ip-address: true
    #将status中得内容显示为“IP:端口“
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      #注册中心得地址
      defaultZone: http://localhost:8761/eureka/