server:
  port: 7900
  contextPath: /
spring:
  application:
    name: apchy-order
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/apchy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: admin
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      logSlowSql: true
      wall:
        config:
          multiStatementAllow: true
eureka:
  instance:
    #是否显示主机得IP
    perfer-ip-address: true
    #将status中得内容显示为“IP:端口“
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      #注册中心得地址
      defaultZone: http://localhost:8761/eureka/
#txmanager地址
tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/