server:
  port: 6666
  contextPath: /
spring:
  application:
    name: apchy-mq
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
    publisher-confirms: true
    virtual-host: /
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: