server:
  port: 6666
  contextPath: /
spring:
  application:
    name: apchy-mq
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
    publisher-confirms: true
    virtual-host: /
