server:
  port: 8090
  contextPath: /
spring:
  application:
    name: apchy-web
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false