server:
  port: 8090
  contextPath: /
spring:
  application:
    name: apchy-web
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  devtools:
    restart:
      enabled: false
      exclude: static/**,templates/**,note.txt
  mvc:
    favicon:
      enabled: false
  datasource:
    master:
      url: jdbc:mysql://47.96.18.156:3306/springboot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: admin
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      logSlowSql: true
      wall:
        config:
          multiStatementAllow: true